[1m============================= test session starts ==============================[0m
platform linux -- Python 3.11.10, pytest-7.4.4, pluggy-1.0.0 -- /opt/conda/envs/sage/bin/python
cachedir: .pytest_cache
rootdir: /home/tjy/SAGE
plugins: typeguard-4.3.0, mock-3.14.1, anyio-4.6.0
[1mcollecting ... [0mcollected 12 items

sage/utils/mmap_queue/tests/test_comprehensive.py::test_edge_cases [32mPASSED[0m[33m [  8%][0m
sage/utils/mmap_queue/tests/test_comprehensive.py::test_concurrent_access [32mPASSED[0m[33m [ 16%][0m
sage/utils/mmap_queue/tests/test_comprehensive.py::test_memory_leak [32mPASSED[0m[33m [ 25%][0m
sage/utils/mmap_queue/tests/test_comprehensive.py::test_persistence [32mPASSED[0m[33m [ 33%][0m
sage/utils/mmap_queue/tests/test_comprehensive.py::test_stress_performance [32mPASSED[0m[33m [ 41%][0m
sage/utils/mmap_queue/tests/test_comprehensive.py::test_multiprocess_robustness [32mPASSED[0m[33m [ 50%][0m
sage/utils/mmap_queue/tests/test_multiprocess_concurrent.py::test_multiprocess_producer_consumer [32mPASSED[0m[33m [ 58%][0m
sage/utils/mmap_queue/tests/test_multiprocess_concurrent.py::test_concurrent_read_write [32mPASSED[0m[33m [ 66%][0m
sage/utils/mmap_queue/tests/test_multiprocess_concurrent.py::test_queue_reference_passing [32mPASSED[0m[33m [ 75%][0m
sage/utils/mmap_queue/tests/test_ray_integration.py::test_simple_producer_consumer [32mPASSED[0m[33m [ 83%][0m
sage/utils/mmap_queue/tests/test_ray_integration.py::test_multiple_producers_consumers [32mPASSED[0m[33m [ 91%][0m
sage/utils/mmap_queue/tests/test_ray_integration.py::test_pipeline_processing [32mPASSED[0m[33m [100%][0m

[33m=============================== warnings summary ===============================[0m
sage/utils/mmap_queue/tests/test_comprehensive.py:30
  /home/tjy/SAGE/sage/utils/mmap_queue/tests/test_comprehensive.py:30: PytestCollectionWarning: cannot collect test class 'TestResult' because it has a __init__ constructor (from: sage/utils/mmap_queue/tests/test_comprehensive.py)
    class TestResult:

sage/utils/mmap_queue/tests/test_comprehensive.py::test_edge_cases
  /opt/conda/envs/sage/lib/python3.11/site-packages/_pytest/python.py:198: PytestReturnNotNoneWarning: Expected None, but sage/utils/mmap_queue/tests/test_comprehensive.py::test_edge_cases returned <sage.utils.mmap_queue.tests.test_comprehensive.TestResult object at 0x7fe7a7d54550>, which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
    warnings.warn(

sage/utils/mmap_queue/tests/test_comprehensive.py::test_concurrent_access
  /opt/conda/envs/sage/lib/python3.11/site-packages/_pytest/python.py:198: PytestReturnNotNoneWarning: Expected None, but sage/utils/mmap_queue/tests/test_comprehensive.py::test_concurrent_access returned <sage.utils.mmap_queue.tests.test_comprehensive.TestResult object at 0x7fe7a7c29150>, which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
    warnings.warn(

sage/utils/mmap_queue/tests/test_comprehensive.py::test_memory_leak
  /opt/conda/envs/sage/lib/python3.11/site-packages/_pytest/python.py:198: PytestReturnNotNoneWarning: Expected None, but sage/utils/mmap_queue/tests/test_comprehensive.py::test_memory_leak returned <sage.utils.mmap_queue.tests.test_comprehensive.TestResult object at 0x7fe7a7c29750>, which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
    warnings.warn(

sage/utils/mmap_queue/tests/test_comprehensive.py::test_persistence
  /opt/conda/envs/sage/lib/python3.11/site-packages/_pytest/python.py:198: PytestReturnNotNoneWarning: Expected None, but sage/utils/mmap_queue/tests/test_comprehensive.py::test_persistence returned <sage.utils.mmap_queue.tests.test_comprehensive.TestResult object at 0x7fe7a7c29c50>, which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
    warnings.warn(

sage/utils/mmap_queue/tests/test_comprehensive.py::test_stress_performance
  /opt/conda/envs/sage/lib/python3.11/site-packages/_pytest/python.py:198: PytestReturnNotNoneWarning: Expected None, but sage/utils/mmap_queue/tests/test_comprehensive.py::test_stress_performance returned <sage.utils.mmap_queue.tests.test_comprehensive.TestResult object at 0x7fe7a7c2a1d0>, which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
    warnings.warn(

sage/utils/mmap_queue/tests/test_comprehensive.py::test_multiprocess_robustness
  /opt/conda/envs/sage/lib/python3.11/site-packages/_pytest/python.py:198: PytestReturnNotNoneWarning: Expected None, but sage/utils/mmap_queue/tests/test_comprehensive.py::test_multiprocess_robustness returned <sage.utils.mmap_queue.tests.test_comprehensive.TestResult object at 0x7fe7a7c29a50>, which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
[33m======================== [32m12 passed[0m, [33m[1m7 warnings[0m[33m in 0.48s[0m[33m ========================[0m
